package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiEventDescriptor{name=ACPI_DEVICE_OST, data={info=ACPIOSTInfo}}</pre></p>
 */
// QApiEventDescriptor{name=ACPI_DEVICE_OST, data={info=ACPIOSTInfo}}
public class AcpiDeviceOstEvent extends QApiEvent {
	@JsonProperty("info")
	@Nonnull
	public ACPIOSTInfo info;
}
