package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiCommandDescriptor{name=add_client, returns=null, data={protocol=str, fdname=str, *skipauth=bool, *tls=bool}}</pre></p>
 */
// QApiCommandDescriptor{name=add_client, returns=null, data={protocol=str, fdname=str, *skipauth=bool, *tls=bool}}
public class AddClientCommand extends QApiCommand<AddClientCommand.Arguments, AddClientCommand.Response> {
	/** Compound arguments to a AddClientCommand. */
	public static class Arguments {

		@SerializedName("protocol")
		@Nonnull
		public java.lang.String protocol;
		@SerializedName("fdname")
		@Nonnull
		public java.lang.String fdname;
		@SerializedName("skipauth")
		@CheckForNull
		public boolean skipauth;
		@SerializedName("tls")
		@CheckForNull
		public boolean tls;

		public Arguments() {
		}

		public Arguments(java.lang.String protocol, java.lang.String fdname, boolean skipauth, boolean tls) {
			this.protocol = protocol;
			this.fdname = fdname;
			this.skipauth = skipauth;
			this.tls = tls;
		}
	}

	/** Response to a AddClientCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new AddClientCommand. */
	public AddClientCommand(@Nonnull AddClientCommand.Arguments argument) {
		super("add_client", Response.class, argument);
	}

	public AddClientCommand(
		java.lang.String protocol, java.lang.String fdname, boolean skipauth, boolean tls			) {
		this(new Arguments(protocol, fdname, skipauth, tls));
	}
}
