package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiEventDescriptor{name=BALLOON_CHANGE, data={actual=int}}</pre></p>
 */
// QApiEventDescriptor{name=BALLOON_CHANGE, data={actual=int}}
public class BalloonChangeEvent extends QApiEvent {
	@SerializedName("actual")
	@Nonnull public long actual;
}
