package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiCommandDescriptor{name=balloon, returns=null, data={value=int}}</pre></p>
 */
// QApiCommandDescriptor{name=balloon, returns=null, data={value=int}}
public class BalloonCommand extends QApiCommand<BalloonCommand.Arguments, BalloonCommand.Response> {
	/** Compound arguments to a BalloonCommand. */
	public static class Arguments {
		@SerializedName("value")
		@Nonnull public long value;
	}

	/** Response to a BalloonCommand. */
	public static class Response extends QApiResponse<Void> {
	}

	/** Constructs a new BalloonCommand. */
	public BalloonCommand(@Nonnull BalloonCommand.Arguments argument) {
		super("balloon", Response.class, argument);
	}
}
