package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiEnumDescriptor{name=BlockdevDiscardOptions, data=[ignore, unmap], fields=null}</pre></p>
 */
// QApiEnumDescriptor{name=BlockdevDiscardOptions, data=[ignore, unmap], fields=null}
public enum BlockdevDiscardOptions {
	@SerializedName("ignore")
	ignore,
	@SerializedName("unmap")
	unmap,
	__UNKNOWN;
}
