package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiTypeDescriptor{name=BlockJobInfo, data={type=str, device=str, len=int, offset=int, busy=bool, paused=bool, speed=int, io-status=BlockDeviceIoStatus}, innerTypes=null}</pre></p>
 */
// QApiTypeDescriptor{name=BlockJobInfo, data={type=str, device=str, len=int, offset=int, busy=bool, paused=bool, speed=int, io-status=BlockDeviceIoStatus}, innerTypes=null}
public class BlockJobInfo extends QApiType {

	@SerializedName("type")
	@Nonnull
	public java.lang.String type;
	@SerializedName("device")
	@Nonnull
	public java.lang.String device;
	@SerializedName("len")
	@Nonnull
	public long len;
	@SerializedName("offset")
	@Nonnull
	public long offset;
	@SerializedName("busy")
	@Nonnull
	public boolean busy;
	@SerializedName("paused")
	@Nonnull
	public boolean paused;
	@SerializedName("speed")
	@Nonnull
	public long speed;
	@SerializedName("io-status")
	@Nonnull
	public BlockDeviceIoStatus ioStatus;
}
