package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiTypeDescriptor{name=BlockdevOptionsBlkdebug, data={image=BlockdevRef, *config=str, *align=int, *inject-error=[BlkdebugInjectErrorOptions], *set-state=[BlkdebugSetStateOptions]}, innerTypes=null}</pre></p>
 */
// QApiTypeDescriptor{name=BlockdevOptionsBlkdebug, data={image=BlockdevRef, *config=str, *align=int, *inject-error=[BlkdebugInjectErrorOptions], *set-state=[BlkdebugSetStateOptions]}, innerTypes=null}
public class BlockdevOptionsBlkdebug extends QApiType {

	@SerializedName("image")
	@Nonnull
	public BlockdevRef image;
	@SerializedName("config")
	@CheckForNull
	public java.lang.String config;
	@SerializedName("align")
	@CheckForNull
	public long align;
	@SerializedName("inject-error")
	@CheckForNull
	public List<BlkdebugInjectErrorOptions> injectError;
	@SerializedName("set-state")
	@CheckForNull
	public List<BlkdebugSetStateOptions> setState;

	public BlockdevOptionsBlkdebug() {
	}

	public BlockdevOptionsBlkdebug(BlockdevRef image, java.lang.String config, long align, List<BlkdebugInjectErrorOptions> injectError, List<BlkdebugSetStateOptions> setState) {
		this.image = image;
		this.config = config;
		this.align = align;
		this.injectError = injectError;
		this.setState = setState;
	}
}
