package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiEnumDescriptor{name=BlockErrorAction, data=[ignore, report, stop], fields=null}</pre></p>
 */
// QApiEnumDescriptor{name=BlockErrorAction, data=[ignore, report, stop], fields=null}
public enum BlockErrorAction {
	@SerializedName("ignore")
	ignore,
	@SerializedName("report")
	report,
	@SerializedName("stop")
	stop,
	__UNKNOWN;
}
