package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiCommandDescriptor{name=block_resize, returns=null, data={*device=str, *node-name=str, size=int}}</pre></p>
 */
// QApiCommandDescriptor{name=block_resize, returns=null, data={*device=str, *node-name=str, size=int}}
public class BlockResizeCommand extends QApiCommand<BlockResizeCommand.Arguments, BlockResizeCommand.Response> {
	/** Compound arguments to a BlockResizeCommand. */
	public static class Arguments {
		@SerializedName("device")
		@CheckForNull
		public java.lang.String device;
		@SerializedName("node-name")
		@CheckForNull
		public java.lang.String nodeName;
		@SerializedName("size")
		@Nonnull
		public long size;
	}

	/** Response to a BlockResizeCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new BlockResizeCommand. */
	public BlockResizeCommand(@Nonnull BlockResizeCommand.Arguments argument) {
		super("block_resize", Response.class, argument);
	}
}
