package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiCommandDescriptor{name=block-job-complete, returns=null, data={device=str}}</pre></p>
 */
// QApiCommandDescriptor{name=block-job-complete, returns=null, data={device=str}}
public class BlockJobCompleteCommand extends QApiCommand<BlockJobCompleteCommand.Arguments, BlockJobCompleteCommand.Response> {
	/** Compound arguments to a BlockJobCompleteCommand. */
	public static class Arguments {

		@JsonProperty("device")
		@Nonnull
		public java.lang.String device;

		public Arguments() {
		}

		public Arguments(java.lang.String device) {
			this.device = device;
		}
	}

	/** Response to a BlockJobCompleteCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new BlockJobCompleteCommand. */
	public BlockJobCompleteCommand(@Nonnull BlockJobCompleteCommand.Arguments argument) {
		super("block-job-complete", Response.class, argument);
	}

	/** Constructs a new BlockJobCompleteCommand. */
	public BlockJobCompleteCommand(java.lang.String device) {
		this(new Arguments(device));
	}
}
