package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiCommandDescriptor{name=blockdev-snapshot-delete-internal-sync, returns=SnapshotInfo, data={device=str, *id=str, *name=str}}</pre></p>
 */
// QApiCommandDescriptor{name=blockdev-snapshot-delete-internal-sync, returns=SnapshotInfo, data={device=str, *id=str, *name=str}}
public class BlockdevSnapshotDeleteInternalSyncCommand extends QApiCommand<BlockdevSnapshotDeleteInternalSyncCommand.Arguments, BlockdevSnapshotDeleteInternalSyncCommand.Response> {
	/** Compound arguments to a BlockdevSnapshotDeleteInternalSyncCommand. */
	public static class Arguments {
		@SerializedName("device")
		@Nonnull
		public java.lang.String device;
		@SerializedName("id")
		@CheckForNull
		public java.lang.String id;
		@SerializedName("name")
		@CheckForNull
		public java.lang.String name;
	}

	/** Response to a BlockdevSnapshotDeleteInternalSyncCommand. */
	public static class Response extends QApiResponse<SnapshotInfo> {
	}

	/** Constructs a new BlockdevSnapshotDeleteInternalSyncCommand. */
	public BlockdevSnapshotDeleteInternalSyncCommand(@Nonnull BlockdevSnapshotDeleteInternalSyncCommand.Arguments argument) {
		super("blockdev-snapshot-delete-internal-sync", Response.class, argument);
	}
}
