package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiCommandDescriptor{name=chardev-remove, returns=null, data={id=str}}</pre></p>
 */
// QApiCommandDescriptor{name=chardev-remove, returns=null, data={id=str}}
public class ChardevRemoveCommand extends QApiCommand<ChardevRemoveCommand.Arguments, ChardevRemoveCommand.Response> {
	/** Compound arguments to a ChardevRemoveCommand. */
	public static class Arguments {
		@SerializedName("id")
		@Nonnull public String id;
	}

	/** Response to a ChardevRemoveCommand. */
	public static class Response extends QApiResponse<Void> {
	}

	/** Constructs a new ChardevRemoveCommand. */
	public ChardevRemoveCommand(@Nonnull ChardevRemoveCommand.Arguments argument) {
		super("chardev-remove", Response.class, argument);
	}
}
