package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiTypeDescriptor{name=CommandInfo, data={name=str}, innerTypes=null}</pre></p>
 */
// QApiTypeDescriptor{name=CommandInfo, data={name=str}, innerTypes=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class CommandInfo extends QApiType {

	@JsonProperty("name")
	@Nonnull
	public java.lang.String name;

	@Nonnull
	public CommandInfo withName(java.lang.String value) {
		this.name = value;
		return this;
	}

	public CommandInfo() {
	}

	public CommandInfo(java.lang.String name) {
		this.name = name;
	}
}
