package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiCommandDescriptor{name=device_del, returns=null, data={id=str}}</pre></p>
 */
// QApiCommandDescriptor{name=device_del, returns=null, data={id=str}}
public class DeviceDelCommand extends QApiCommand<DeviceDelCommand.Arguments, DeviceDelCommand.Response> {
	/** Compound arguments to a DeviceDelCommand. */
	public static class Arguments {

		@JsonProperty("id")
		@Nonnull
		public java.lang.String id;

		public Arguments() {
		}

		public Arguments(java.lang.String id) {
			this.id = id;
		}
	}

	/** Response to a DeviceDelCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new DeviceDelCommand. */
	public DeviceDelCommand(@Nonnull DeviceDelCommand.Arguments argument) {
		super("device_del", Response.class, argument);
	}

	/** Constructs a new DeviceDelCommand. */
	public DeviceDelCommand(java.lang.String id) {
		this(new Arguments(id));
	}
}
