package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiEnumDescriptor{name=GuestPanicAction, data=[pause], fields=null}</pre></p>
 */
// QApiEnumDescriptor{name=GuestPanicAction, data=[pause], fields=null}
public enum GuestPanicAction {
	@SerializedName("pause")
	pause,
	__UNKNOWN;
}
