package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiTypeDescriptor{name=InetSocketAddress, data={host=str, port=str, *to=uint16, *ipv4=bool, *ipv6=bool}, innerTypes=null}</pre></p>
 */
// QApiTypeDescriptor{name=InetSocketAddress, data={host=str, port=str, *to=uint16, *ipv4=bool, *ipv6=bool}, innerTypes=null}
public class InetSocketAddress extends QApiType {

	@SerializedName("host")
	@Nonnull
	public java.lang.String host;
	@SerializedName("port")
	@Nonnull
	public java.lang.String port;
	@SerializedName("to")
	@CheckForNull
	public int to;
	@SerializedName("ipv4")
	@CheckForNull
	public boolean ipv4;
	@SerializedName("ipv6")
	@CheckForNull
	public boolean ipv6;

	public InetSocketAddress() {
	}

	public InetSocketAddress(java.lang.String host, java.lang.String port, int to, boolean ipv4, boolean ipv6) {
		this.host = host;
		this.port = port;
		this.to = to;
		this.ipv4 = ipv4;
		this.ipv6 = ipv6;
	}
}
