package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiTypeDescriptor{name=MigrationInfo, data={*status=str, *ram=MigrationStats, *disk=MigrationStats, *xbzrle-cache=XBZRLECacheStats, *total-time=int, *expected-downtime=int, *downtime=int, *setup-time=int}, innerTypes=null}</pre></p>
 */
// QApiTypeDescriptor{name=MigrationInfo, data={*status=str, *ram=MigrationStats, *disk=MigrationStats, *xbzrle-cache=XBZRLECacheStats, *total-time=int, *expected-downtime=int, *downtime=int, *setup-time=int}, innerTypes=null}
public class MigrationInfo extends QApiType {

	@SerializedName("status")
	@CheckForNull
	public java.lang.String status;
	@SerializedName("ram")
	@CheckForNull
	public MigrationStats ram;
	@SerializedName("disk")
	@CheckForNull
	public MigrationStats disk;
	@SerializedName("xbzrle-cache")
	@CheckForNull
	public XBZRLECacheStats xbzrleCache;
	@SerializedName("total-time")
	@CheckForNull
	public long totalTime;
	@SerializedName("expected-downtime")
	@CheckForNull
	public long expectedDowntime;
	@SerializedName("downtime")
	@CheckForNull
	public long downtime;
	@SerializedName("setup-time")
	@CheckForNull
	public long setupTime;

	public MigrationInfo() {
	}

	public MigrationInfo(java.lang.String status, MigrationStats ram, MigrationStats disk, XBZRLECacheStats xbzrleCache, long totalTime, long expectedDowntime, long downtime, long setupTime) {
		this.status = status;
		this.ram = ram;
		this.disk = disk;
		this.xbzrleCache = xbzrleCache;
		this.totalTime = totalTime;
		this.expectedDowntime = expectedDowntime;
		this.downtime = downtime;
		this.setupTime = setupTime;
	}
}
