package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiTypeDescriptor{name=NetdevUserOptions, data={*hostname=str, *restrict=bool, *ip=str, *net=str, *host=str, *tftp=str, *bootfile=str, *dhcpstart=str, *dns=str, *dnssearch=[String], *smb=str, *smbserver=str, *hostfwd=[String], *guestfwd=[String]}, innerTypes=null}</pre></p>
 */
// QApiTypeDescriptor{name=NetdevUserOptions, data={*hostname=str, *restrict=bool, *ip=str, *net=str, *host=str, *tftp=str, *bootfile=str, *dhcpstart=str, *dns=str, *dnssearch=[String], *smb=str, *smbserver=str, *hostfwd=[String], *guestfwd=[String]}, innerTypes=null}
public class NetdevUserOptions extends QApiType {

	@SerializedName("hostname")
	@CheckForNull
	public java.lang.String hostname;
	@SerializedName("restrict")
	@CheckForNull
	public boolean restrict;
	@SerializedName("ip")
	@CheckForNull
	public java.lang.String ip;
	@SerializedName("net")
	@CheckForNull
	public java.lang.String net;
	@SerializedName("host")
	@CheckForNull
	public java.lang.String host;
	@SerializedName("tftp")
	@CheckForNull
	public java.lang.String tftp;
	@SerializedName("bootfile")
	@CheckForNull
	public java.lang.String bootfile;
	@SerializedName("dhcpstart")
	@CheckForNull
	public java.lang.String dhcpstart;
	@SerializedName("dns")
	@CheckForNull
	public java.lang.String dns;
	@SerializedName("dnssearch")
	@CheckForNull
	public List<String> dnssearch;
	@SerializedName("smb")
	@CheckForNull
	public java.lang.String smb;
	@SerializedName("smbserver")
	@CheckForNull
	public java.lang.String smbserver;
	@SerializedName("hostfwd")
	@CheckForNull
	public List<String> hostfwd;
	@SerializedName("guestfwd")
	@CheckForNull
	public List<String> guestfwd;

	public NetdevUserOptions() {
	}

	public NetdevUserOptions(java.lang.String hostname, boolean restrict, java.lang.String ip, java.lang.String net, java.lang.String host, java.lang.String tftp, java.lang.String bootfile, java.lang.String dhcpstart, java.lang.String dns, List<String> dnssearch, java.lang.String smb, java.lang.String smbserver, List<String> hostfwd, List<String> guestfwd) {
		this.hostname = hostname;
		this.restrict = restrict;
		this.ip = ip;
		this.net = net;
		this.host = host;
		this.tftp = tftp;
		this.bootfile = bootfile;
		this.dhcpstart = dhcpstart;
		this.dns = dns;
		this.dnssearch = dnssearch;
		this.smb = smb;
		this.smbserver = smbserver;
		this.hostfwd = hostfwd;
		this.guestfwd = guestfwd;
	}
}
