package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiTypeDescriptor{name=NetdevSocketOptions, data={*fd=str, *listen=str, *connect=str, *mcast=str, *localaddr=str, *udp=str}, innerTypes=null}</pre></p>
 */
// QApiTypeDescriptor{name=NetdevSocketOptions, data={*fd=str, *listen=str, *connect=str, *mcast=str, *localaddr=str, *udp=str}, innerTypes=null}
public class NetdevSocketOptions extends QApiType {

	@SerializedName("fd")
	@CheckForNull
	public java.lang.String fd;
	@SerializedName("listen")
	@CheckForNull
	public java.lang.String listen;
	@SerializedName("connect")
	@CheckForNull
	public java.lang.String connect;
	@SerializedName("mcast")
	@CheckForNull
	public java.lang.String mcast;
	@SerializedName("localaddr")
	@CheckForNull
	public java.lang.String localaddr;
	@SerializedName("udp")
	@CheckForNull
	public java.lang.String udp;

	public NetdevSocketOptions() {
	}

	public NetdevSocketOptions(java.lang.String fd, java.lang.String listen, java.lang.String connect, java.lang.String mcast, java.lang.String localaddr, java.lang.String udp) {
		this.fd = fd;
		this.listen = listen;
		this.connect = connect;
		this.mcast = mcast;
		this.localaddr = localaddr;
		this.udp = udp;
	}
}
