package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiTypeDescriptor{name=NetLegacy, data={*vlan=int32, *id=str, *name=str, opts=NetClientOptions}, innerTypes=null}</pre></p>
 */
// QApiTypeDescriptor{name=NetLegacy, data={*vlan=int32, *id=str, *name=str, opts=NetClientOptions}, innerTypes=null}
public class NetLegacy extends QApiType {

	@SerializedName("vlan")
	@CheckForNull
	public int vlan;
	@SerializedName("id")
	@CheckForNull
	public java.lang.String id;
	@SerializedName("name")
	@CheckForNull
	public java.lang.String name;
	@SerializedName("opts")
	@Nonnull
	public NetClientOptions opts;

	public NetLegacy() {
	}

	public NetLegacy(int vlan, java.lang.String id, java.lang.String name, NetClientOptions opts) {
		this.vlan = vlan;
		this.id = id;
		this.name = name;
		this.opts = opts;
	}
}
