package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;

// QApiEnumDescriptor{name=QKeyCode, data=[unmapped, shift, shift_r, alt, alt_r, altgr, altgr_r, ctrl, ctrl_r, menu, esc, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, minus, equal, backspace, tab, q, w, e, r, t, y, u, i, o, p, bracket_left, bracket_right, ret, a, s, d, f, g, h, j, k, l, semicolon, apostrophe, grave_accent, backslash, z, x, c, v, b, n, m, comma, dot, slash, asterisk, spc, caps_lock, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, num_lock, scroll_lock, kp_divide, kp_multiply, kp_subtract, kp_add, kp_enter, kp_decimal, sysrq, kp_0, kp_1, kp_2, kp_3, kp_4, kp_5, kp_6, kp_7, kp_8, kp_9, less, f11, f12, print, home, pgup, pgdn, end, left, up, down, right, insert, delete, stop, again, props, undo, front, copy, open, paste, find, cut, lf, help, meta_l, meta_r, compose, pause], fields=null}
public enum QKeyCode {
	@SerializedName("unmapped")
	unmapped,
	@SerializedName("shift")
	shift,
	@SerializedName("shift_r")
	shift_r,
	@SerializedName("alt")
	alt,
	@SerializedName("alt_r")
	alt_r,
	@SerializedName("altgr")
	altgr,
	@SerializedName("altgr_r")
	altgr_r,
	@SerializedName("ctrl")
	ctrl,
	@SerializedName("ctrl_r")
	ctrl_r,
	@SerializedName("menu")
	menu,
	@SerializedName("esc")
	esc,
	@SerializedName("1")
	VAL_1,
	@SerializedName("2")
	VAL_2,
	@SerializedName("3")
	VAL_3,
	@SerializedName("4")
	VAL_4,
	@SerializedName("5")
	VAL_5,
	@SerializedName("6")
	VAL_6,
	@SerializedName("7")
	VAL_7,
	@SerializedName("8")
	VAL_8,
	@SerializedName("9")
	VAL_9,
	@SerializedName("0")
	VAL_0,
	@SerializedName("minus")
	minus,
	@SerializedName("equal")
	equal,
	@SerializedName("backspace")
	backspace,
	@SerializedName("tab")
	tab,
	@SerializedName("q")
	q,
	@SerializedName("w")
	w,
	@SerializedName("e")
	e,
	@SerializedName("r")
	r,
	@SerializedName("t")
	t,
	@SerializedName("y")
	y,
	@SerializedName("u")
	u,
	@SerializedName("i")
	i,
	@SerializedName("o")
	o,
	@SerializedName("p")
	p,
	@SerializedName("bracket_left")
	bracket_left,
	@SerializedName("bracket_right")
	bracket_right,
	@SerializedName("ret")
	ret,
	@SerializedName("a")
	a,
	@SerializedName("s")
	s,
	@SerializedName("d")
	d,
	@SerializedName("f")
	f,
	@SerializedName("g")
	g,
	@SerializedName("h")
	h,
	@SerializedName("j")
	j,
	@SerializedName("k")
	k,
	@SerializedName("l")
	l,
	@SerializedName("semicolon")
	semicolon,
	@SerializedName("apostrophe")
	apostrophe,
	@SerializedName("grave_accent")
	grave_accent,
	@SerializedName("backslash")
	backslash,
	@SerializedName("z")
	z,
	@SerializedName("x")
	x,
	@SerializedName("c")
	c,
	@SerializedName("v")
	v,
	@SerializedName("b")
	b,
	@SerializedName("n")
	n,
	@SerializedName("m")
	m,
	@SerializedName("comma")
	comma,
	@SerializedName("dot")
	dot,
	@SerializedName("slash")
	slash,
	@SerializedName("asterisk")
	asterisk,
	@SerializedName("spc")
	spc,
	@SerializedName("caps_lock")
	caps_lock,
	@SerializedName("f1")
	f1,
	@SerializedName("f2")
	f2,
	@SerializedName("f3")
	f3,
	@SerializedName("f4")
	f4,
	@SerializedName("f5")
	f5,
	@SerializedName("f6")
	f6,
	@SerializedName("f7")
	f7,
	@SerializedName("f8")
	f8,
	@SerializedName("f9")
	f9,
	@SerializedName("f10")
	f10,
	@SerializedName("num_lock")
	num_lock,
	@SerializedName("scroll_lock")
	scroll_lock,
	@SerializedName("kp_divide")
	kp_divide,
	@SerializedName("kp_multiply")
	kp_multiply,
	@SerializedName("kp_subtract")
	kp_subtract,
	@SerializedName("kp_add")
	kp_add,
	@SerializedName("kp_enter")
	kp_enter,
	@SerializedName("kp_decimal")
	kp_decimal,
	@SerializedName("sysrq")
	sysrq,
	@SerializedName("kp_0")
	kp_0,
	@SerializedName("kp_1")
	kp_1,
	@SerializedName("kp_2")
	kp_2,
	@SerializedName("kp_3")
	kp_3,
	@SerializedName("kp_4")
	kp_4,
	@SerializedName("kp_5")
	kp_5,
	@SerializedName("kp_6")
	kp_6,
	@SerializedName("kp_7")
	kp_7,
	@SerializedName("kp_8")
	kp_8,
	@SerializedName("kp_9")
	kp_9,
	@SerializedName("less")
	less,
	@SerializedName("f11")
	f11,
	@SerializedName("f12")
	f12,
	@SerializedName("print")
	print,
	@SerializedName("home")
	home,
	@SerializedName("pgup")
	pgup,
	@SerializedName("pgdn")
	pgdn,
	@SerializedName("end")
	end,
	@SerializedName("left")
	left,
	@SerializedName("up")
	up,
	@SerializedName("down")
	down,
	@SerializedName("right")
	right,
	@SerializedName("insert")
	insert,
	@SerializedName("delete")
	delete,
	@SerializedName("stop")
	stop,
	@SerializedName("again")
	again,
	@SerializedName("props")
	props,
	@SerializedName("undo")
	undo,
	@SerializedName("front")
	front,
	@SerializedName("copy")
	copy,
	@SerializedName("open")
	open,
	@SerializedName("paste")
	paste,
	@SerializedName("find")
	find,
	@SerializedName("cut")
	cut,
	@SerializedName("lf")
	lf,
	@SerializedName("help")
	help,
	@SerializedName("meta_l")
	meta_l,
	@SerializedName("meta_r")
	meta_r,
	@SerializedName("compose")
	compose,
	@SerializedName("pause")
	pause,
	__UNKNOWN;
}
