package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiCommandDescriptor{name=query-memdev, returns=[Memdev], data=null}</pre></p>
 */
// QApiCommandDescriptor{name=query-memdev, returns=[Memdev], data=null}
public class QueryMemdevCommand extends QApiCommand<java.lang.Void, QueryMemdevCommand.Response> {

	/** Response to a QueryMemdevCommand. */
	public static class Response extends QApiResponse<List<Memdev>> {
	}

	/** Constructs a new QueryMemdevCommand. */
	public QueryMemdevCommand() {
		super("query-memdev", Response.class, null);
	}

}
