package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiCommandDescriptor{name=query-chardev-backends, returns=[ChardevBackendInfo], data=null}</pre></p>
 */
// QApiCommandDescriptor{name=query-chardev-backends, returns=[ChardevBackendInfo], data=null}
public class QueryChardevBackendsCommand extends QApiCommand<java.lang.Void, QueryChardevBackendsCommand.Response> {

	/** Response to a QueryChardevBackendsCommand. */
	public static class Response extends QApiResponse<List<ChardevBackendInfo>> {
	}

	/** Constructs a new QueryChardevBackendsCommand. */
	public QueryChardevBackendsCommand() {
		super("query-chardev-backends", Response.class, null);
	}
}
