package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiCommandDescriptor{name=query-block, returns=[BlockInfo], data=null}</pre></p>
 */
// QApiCommandDescriptor{name=query-block, returns=[BlockInfo], data=null}
public class QueryBlockCommand extends QApiCommand<java.lang.Void, QueryBlockCommand.Response> {

	/** Response to a QueryBlockCommand. */
	public static class Response extends QApiResponse<java.util.List<BlockInfo>> {
	}

	/** Constructs a new QueryBlockCommand. */
	public QueryBlockCommand() {
		super("query-block", Response.class, null);
	}

}
