package org.anarres.qemu.qapi.api;

import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import java.util.List;
import java.util.Map;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiCommandDescriptor{name=query-spice, returns=SpiceInfo, data=null}</pre></p>
 */
// QApiCommandDescriptor{name=query-spice, returns=SpiceInfo, data=null}
public class QuerySpiceCommand extends QApiCommand<java.lang.Void, QuerySpiceCommand.Response> {

	/** Response to a QuerySpiceCommand. */
	public static class Response extends QApiResponse<SpiceInfo> {
	}

	/** Constructs a new QuerySpiceCommand. */
	public QuerySpiceCommand() {
		super("query-spice", Response.class, null);
	}

}
