package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiEnumDescriptor{name=RunState, data=[debug, inmigrate, internal-error, io-error, paused, postmigrate, prelaunch, finish-migrate, restore-vm, running, save-vm, shutdown, suspended, watchdog, guest-panicked], fields=null}</pre></p>
 */
// QApiEnumDescriptor{name=RunState, data=[debug, inmigrate, internal-error, io-error, paused, postmigrate, prelaunch, finish-migrate, restore-vm, running, save-vm, shutdown, suspended, watchdog, guest-panicked], fields=null}
public enum RunState {
	// @JsonProperty("debug")
	debug("debug"),
	// @JsonProperty("inmigrate")
	inmigrate("inmigrate"),
	// @JsonProperty("internal-error")
	internal_error("internal-error"),
	// @JsonProperty("io-error")
	io_error("io-error"),
	// @JsonProperty("paused")
	paused("paused"),
	// @JsonProperty("postmigrate")
	postmigrate("postmigrate"),
	// @JsonProperty("prelaunch")
	prelaunch("prelaunch"),
	// @JsonProperty("finish-migrate")
	finish_migrate("finish-migrate"),
	// @JsonProperty("restore-vm")
	restore_vm("restore-vm"),
	// @JsonProperty("running")
	running("running"),
	// @JsonProperty("save-vm")
	save_vm("save-vm"),
	// @JsonProperty("shutdown")
	shutdown("shutdown"),
	// @JsonProperty("suspended")
	suspended("suspended"),
	// @JsonProperty("watchdog")
	watchdog("watchdog"),
	// @JsonProperty("guest-panicked")
	guest_panicked("guest-panicked"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ RunState(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
