package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiTypeDescriptor{name=UnixSocketAddress, data={path=str}, innerTypes=null}</pre></p>
 */
// QApiTypeDescriptor{name=UnixSocketAddress, data={path=str}, innerTypes=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class UnixSocketAddress extends QApiType {

	@JsonProperty("path")
	@Nonnull
	public java.lang.String path;

	@Nonnull
	public UnixSocketAddress withPath(java.lang.String value) {
		this.path = value;
		return this;
	}

	public UnixSocketAddress() {
	}

	public UnixSocketAddress(java.lang.String path) {
		this.path = path;
	}
}
