package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiTypeDescriptor{name=VncBasicInfo, data={host=str, service=str, family=NetworkAddressFamily}, innerTypes=null}</pre></p>
 */
// QApiTypeDescriptor{name=VncBasicInfo, data={host=str, service=str, family=NetworkAddressFamily}, innerTypes=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class VncBasicInfo extends QApiType {

	@JsonProperty("host")
	@Nonnull
	public java.lang.String host;
	@JsonProperty("service")
	@Nonnull
	public java.lang.String service;
	@JsonProperty("family")
	@Nonnull
	public NetworkAddressFamily family;

	@Nonnull
	public VncBasicInfo withHost(java.lang.String value) {
		this.host = value;
		return this;
	}

	@Nonnull
	public VncBasicInfo withService(java.lang.String value) {
		this.service = value;
		return this;
	}

	@Nonnull
	public VncBasicInfo withFamily(NetworkAddressFamily value) {
		this.family = value;
		return this;
	}

	public VncBasicInfo() {
	}

	public VncBasicInfo(java.lang.String host, java.lang.String service, NetworkAddressFamily family) {
		this.host = host;
		this.service = service;
		this.family = family;
	}
}
