package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiTypeDescriptor{name=VncClientInfo, data={*x509_dname=str, *sasl_username=str}, innerTypes=null}</pre></p>
 */
// QApiTypeDescriptor{name=VncClientInfo, data={*x509_dname=str, *sasl_username=str}, innerTypes=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class VncClientInfo extends VncBasicInfo {

	@JsonProperty("x509_dname")
	@CheckForNull
	public java.lang.String x509Dname;
	@JsonProperty("sasl_username")
	@CheckForNull
	public java.lang.String saslUsername;

	@Nonnull
	public VncClientInfo withX509Dname(java.lang.String value) {
		this.x509Dname = value;
		return this;
	}

	@Nonnull
	public VncClientInfo withSaslUsername(java.lang.String value) {
		this.saslUsername = value;
		return this;
	}

	public VncClientInfo() {
	}

	public VncClientInfo(java.lang.String x509Dname, java.lang.String saslUsername) {
		this.x509Dname = x509Dname;
		this.saslUsername = saslUsername;
	}
}
