package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiEventDescriptor{name=WATCHDOG, data={action=WatchdogExpirationAction}}</pre></p>
 */
// QApiEventDescriptor{name=WATCHDOG, data={action=WatchdogExpirationAction}}
public class WatchdogEvent extends QApiEvent {
	@JsonProperty("action")
	@Nonnull
	public WatchdogExpirationAction action;
}
