package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=BALLOON_CHANGE, data={actual=int}}</pre>
 */
// QApiEventDescriptor{name=BALLOON_CHANGE, data={actual=int}}
public class BalloonChangeEvent extends QApiEvent {
	@JsonProperty("actual")
	@Nonnull
	public long actual;
}
