package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiTypeDescriptor{name=BlockdevOptionsGenericCOWFormat, data={*backing=BlockdevRef}, innerTypes=null}</pre>
 */
// QApiTypeDescriptor{name=BlockdevOptionsGenericCOWFormat, data={*backing=BlockdevRef}, innerTypes=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class BlockdevOptionsGenericCOWFormat extends BlockdevOptionsGenericFormat {

	@JsonProperty("backing")
	@CheckForNull
	public BlockdevRef backing;

	@Nonnull
	public BlockdevOptionsGenericCOWFormat withBacking(BlockdevRef value) {
		this.backing = value;
		return this;
	}

	public BlockdevOptionsGenericCOWFormat() {
	}

	public BlockdevOptionsGenericCOWFormat(BlockdevRef backing) {
		this.backing = backing;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("backing");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("backing".equals(name))
			return backing;
		return super.getFieldByName(name);
	}
}
