package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiUnionDescriptor{name=BlockdevQcowEncryption, discriminator=format, data={aes=QCryptoBlockOptionsQCow}, innerTypes=null, fields=null, base={format=BlockdevQcowEncryptionFormat}, discriminatorField=null}</pre>
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class BlockdevQcowEncryption extends BlockdevQcowEncryptionBase implements QApiUnion {

	// union {
	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("aes")
	@JsonUnwrapped
	@CheckForNull
	public QCryptoBlockOptionsQCow aes;
	// }

	@Nonnull
	public static BlockdevQcowEncryption aes(@Nonnull QCryptoBlockOptionsQCow aes) {
		BlockdevQcowEncryption self = new BlockdevQcowEncryption();
		self.format = BlockdevQcowEncryptionFormat.aes;
		self.aes = aes;
		return self;
	}

	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("aes");
		return names;
	}

	@JsonIgnore
	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("aes".equals(name))
			return aes;
		return super.getFieldByName(name);
	}

	@JsonIgnore
	public boolean isValidUnion() {
		int count = 0;
		if (aes != null)
			count++;
		return (count == 1);
	}
}
