package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=block-commit, returns=null, data={device=str, *base=str, *top=str, *backing-file=str, *speed=int}}</pre>
 */
// QApiCommandDescriptor{name=block-commit, returns=null, data={device=str, *base=str, *top=str, *backing-file=str, *speed=int}}
public class BlockCommitCommand extends QApiCommand<BlockCommitCommand.Arguments, BlockCommitCommand.Response> {
	/** Compound arguments to a BlockCommitCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("device")
		@Nonnull
		public java.lang.String device;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("base")
		@CheckForNull
		public java.lang.String base;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("top")
		@CheckForNull
		public java.lang.String top;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("backing-file")
		@CheckForNull
		public java.lang.String backingFile;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("speed")
		@CheckForNull
		public java.lang.Long speed;

		public Arguments() {
		}

		public Arguments(java.lang.String device, java.lang.String base, java.lang.String top, java.lang.String backingFile, java.lang.Long speed) {
			this.device = device;
			this.base = base;
			this.top = top;
			this.backingFile = backingFile;
			this.speed = speed;
		}
	}

	/** Response to a BlockCommitCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new BlockCommitCommand. */
	public BlockCommitCommand(@Nonnull BlockCommitCommand.Arguments argument) {
		super("block-commit", Response.class, argument);
	}

	/** Constructs a new BlockCommitCommand. */
	public BlockCommitCommand(java.lang.String device, java.lang.String base, java.lang.String top, java.lang.String backingFile, java.lang.Long speed) {
		this(new Arguments(device, base, top, backingFile, speed));
	}
}
