package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiStructDescriptor{name=BlockdevOptionsCurlFtps, data={*sslverify=bool}, innerTypes=null, fields=null, base=BlockdevOptionsCurlBase}</pre>
 */
// QApiStructDescriptor{name=BlockdevOptionsCurlFtps, data={*sslverify=bool}, innerTypes=null, fields=null, base=BlockdevOptionsCurlBase}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class BlockdevOptionsCurlFtps extends BlockdevOptionsCurlBase {

	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("sslverify")
	@CheckForNull
	public java.lang.Boolean sslverify;

	@Nonnull
	public BlockdevOptionsCurlFtps withSslverify(java.lang.Boolean value) {
		this.sslverify = value;
		return this;
	}

	public BlockdevOptionsCurlFtps() {
	}

	public BlockdevOptionsCurlFtps(java.lang.Boolean sslverify) {
		this.sslverify = sslverify;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("sslverify");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("sslverify".equals(name))
			return sslverify;
		return super.getFieldByName(name);
	}
}
