package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiEnumDescriptor{name=BlockDeviceIoStatus, data=[ok, failed, nospace], fields=null}</pre></p>
 */
// QApiEnumDescriptor{name=BlockDeviceIoStatus, data=[ok, failed, nospace], fields=null}
public enum BlockDeviceIoStatus {
	// @JsonProperty("ok")
	ok("ok"),
	// @JsonProperty("failed")
	failed("failed"),
	// @JsonProperty("nospace")
	nospace("nospace"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ BlockDeviceIoStatus(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
