package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiStructDescriptor{name=BlockdevOptionsFile, data={filename=str, *pr-manager=str, *locking=OnOffAuto, *aio=BlockdevAioOptions, *x-check-cache-dropped=bool}, innerTypes=null, fields=null, base=null}</pre>
 */
// QApiStructDescriptor{name=BlockdevOptionsFile, data={filename=str, *pr-manager=str, *locking=OnOffAuto, *aio=BlockdevAioOptions, *x-check-cache-dropped=bool}, innerTypes=null, fields=null, base=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class BlockdevOptionsFile extends QApiType {

	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("filename")
	@Nonnull
	public java.lang.String filename;
	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("pr-manager")
	@CheckForNull
	public java.lang.String prManager;
	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("locking")
	@CheckForNull
	public OnOffAuto locking;
	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("aio")
	@CheckForNull
	public BlockdevAioOptions aio;
	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("x-check-cache-dropped")
	@CheckForNull
	public java.lang.Boolean xCheckCacheDropped;

	@Nonnull
	public BlockdevOptionsFile withFilename(java.lang.String value) {
		this.filename = value;
		return this;
	}

	@Nonnull
	public BlockdevOptionsFile withPrManager(java.lang.String value) {
		this.prManager = value;
		return this;
	}

	@Nonnull
	public BlockdevOptionsFile withLocking(OnOffAuto value) {
		this.locking = value;
		return this;
	}

	@Nonnull
	public BlockdevOptionsFile withAio(BlockdevAioOptions value) {
		this.aio = value;
		return this;
	}

	@Nonnull
	public BlockdevOptionsFile withXCheckCacheDropped(java.lang.Boolean value) {
		this.xCheckCacheDropped = value;
		return this;
	}

	public BlockdevOptionsFile() {
	}

	public BlockdevOptionsFile(java.lang.String filename, java.lang.String prManager, OnOffAuto locking, BlockdevAioOptions aio, java.lang.Boolean xCheckCacheDropped) {
		this.filename = filename;
		this.prManager = prManager;
		this.locking = locking;
		this.aio = aio;
		this.xCheckCacheDropped = xCheckCacheDropped;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("filename");
		names.add("pr-manager");
		names.add("locking");
		names.add("aio");
		names.add("x-check-cache-dropped");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("filename".equals(name))
			return filename;
		if ("pr-manager".equals(name))
			return prManager;
		if ("locking".equals(name))
			return locking;
		if ("aio".equals(name))
			return aio;
		if ("x-check-cache-dropped".equals(name))
			return xCheckCacheDropped;
		return super.getFieldByName(name);
	}
}
