package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiStructDescriptor{name=BlockdevOptionsQcow, data={*encrypt=BlockdevQcowEncryption}, innerTypes=null, fields=null, base=BlockdevOptionsGenericCOWFormat}</pre>
 */
// QApiStructDescriptor{name=BlockdevOptionsQcow, data={*encrypt=BlockdevQcowEncryption}, innerTypes=null, fields=null, base=BlockdevOptionsGenericCOWFormat}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class BlockdevOptionsQcow extends BlockdevOptionsGenericCOWFormat {

	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("encrypt")
	@CheckForNull
	public BlockdevQcowEncryption encrypt;

	@Nonnull
	public BlockdevOptionsQcow withEncrypt(BlockdevQcowEncryption value) {
		this.encrypt = value;
		return this;
	}

	public BlockdevOptionsQcow() {
	}

	public BlockdevOptionsQcow(BlockdevQcowEncryption encrypt) {
		this.encrypt = encrypt;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("encrypt");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("encrypt".equals(name))
			return encrypt;
		return super.getFieldByName(name);
	}
}
