package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiEventDescriptor{name=BLOCK_IO_ERROR, data={device=str, operation=IoOperationType, action=BlockErrorAction, *nospace=bool, reason=str}}</pre></p>
 */
// QApiEventDescriptor{name=BLOCK_IO_ERROR, data={device=str, operation=IoOperationType, action=BlockErrorAction, *nospace=bool, reason=str}}
public class BlockIoErrorEvent extends QApiEvent {
	@JsonProperty("device")
	@Nonnull
	public java.lang.String device;
	@JsonProperty("operation")
	@Nonnull
	public IoOperationType operation;
	@JsonProperty("action")
	@Nonnull
	public BlockErrorAction action;
	@JsonProperty("nospace")
	@CheckForNull
	public java.lang.Boolean nospace;
	@JsonProperty("reason")
	@Nonnull
	public java.lang.String reason;
}
