package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=blockdev-change-medium, returns=null, data={*device=str, *id=str, filename=str, *format=str, *read-only-mode=BlockdevChangeReadOnlyMode}}</pre>
 */
// QApiCommandDescriptor{name=blockdev-change-medium, returns=null, data={*device=str, *id=str, filename=str, *format=str, *read-only-mode=BlockdevChangeReadOnlyMode}}
public class BlockdevChangeMediumCommand extends QApiCommand<BlockdevChangeMediumCommand.Arguments, BlockdevChangeMediumCommand.Response> {
	/** Compound arguments to a BlockdevChangeMediumCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("device")
		@CheckForNull
		public java.lang.String device;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("id")
		@CheckForNull
		public java.lang.String id;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("filename")
		@Nonnull
		public java.lang.String filename;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("format")
		@CheckForNull
		public java.lang.String format;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("read-only-mode")
		@CheckForNull
		public BlockdevChangeReadOnlyMode readOnlyMode;

		public Arguments() {
		}

		public Arguments(java.lang.String device, java.lang.String id, java.lang.String filename, java.lang.String format, BlockdevChangeReadOnlyMode readOnlyMode) {
			this.device = device;
			this.id = id;
			this.filename = filename;
			this.format = format;
			this.readOnlyMode = readOnlyMode;
		}
	}

	/** Response to a BlockdevChangeMediumCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new BlockdevChangeMediumCommand. */
	public BlockdevChangeMediumCommand(@Nonnull BlockdevChangeMediumCommand.Arguments argument) {
		super("blockdev-change-medium", Response.class, argument);
	}

	/** Constructs a new BlockdevChangeMediumCommand. */
	public BlockdevChangeMediumCommand(java.lang.String device, java.lang.String id, java.lang.String filename, java.lang.String format, BlockdevChangeReadOnlyMode readOnlyMode) {
		this(new Arguments(device, id, filename, format, readOnlyMode));
	}
}
