package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=block-job-set-speed, returns=null, data={device=str, speed=int}}</pre>
 */
// QApiCommandDescriptor{name=block-job-set-speed, returns=null, data={device=str, speed=int}}
public class BlockJobSetSpeedCommand extends QApiCommand<BlockJobSetSpeedCommand.Arguments, BlockJobSetSpeedCommand.Response> {
	/** Compound arguments to a BlockJobSetSpeedCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("device")
		@Nonnull
		public java.lang.String device;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("speed")
		@Nonnull
		public long speed;

		public Arguments() {
		}

		public Arguments(java.lang.String device, long speed) {
			this.device = device;
			this.speed = speed;
		}
	}

	/** Response to a BlockJobSetSpeedCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new BlockJobSetSpeedCommand. */
	public BlockJobSetSpeedCommand(@Nonnull BlockJobSetSpeedCommand.Arguments argument) {
		super("block-job-set-speed", Response.class, argument);
	}

	/** Constructs a new BlockJobSetSpeedCommand. */
	public BlockJobSetSpeedCommand(java.lang.String device, long speed) {
		this(new Arguments(device, speed));
	}
}
