package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=block-dirty-bitmap-remove, returns=null, data=BlockDirtyBitmap}</pre>
 */
// QApiCommandDescriptor{name=block-dirty-bitmap-remove, returns=null, data=BlockDirtyBitmap}
public class BlockDirtyBitmapRemoveCommand extends QApiCommand<BlockDirtyBitmap, BlockDirtyBitmapRemoveCommand.Response> {

	/** Response to a BlockDirtyBitmapRemoveCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new BlockDirtyBitmapRemoveCommand. */
	public BlockDirtyBitmapRemoveCommand(@Nonnull BlockDirtyBitmap argument) {
		super("block-dirty-bitmap-remove", Response.class, argument);
	}

}
