package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiTypeDescriptor{name=BlockDirtyInfo, data={*name=str, count=int, granularity=uint32, frozen=bool}, innerTypes=null}</pre>
 */
// QApiTypeDescriptor{name=BlockDirtyInfo, data={*name=str, count=int, granularity=uint32, frozen=bool}, innerTypes=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class BlockDirtyInfo extends QApiType {

	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("name")
	@CheckForNull
	public java.lang.String name;
	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("count")
	@Nonnull
	public long count;
	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("granularity")
	@Nonnull
	public long granularity;
	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("frozen")
	@Nonnull
	public boolean frozen;

	@Nonnull
	public BlockDirtyInfo withName(java.lang.String value) {
		this.name = value;
		return this;
	}

	@Nonnull
	public BlockDirtyInfo withCount(long value) {
		this.count = value;
		return this;
	}

	@Nonnull
	public BlockDirtyInfo withGranularity(long value) {
		this.granularity = value;
		return this;
	}

	@Nonnull
	public BlockDirtyInfo withFrozen(boolean value) {
		this.frozen = value;
		return this;
	}

	public BlockDirtyInfo() {
	}

	public BlockDirtyInfo(java.lang.String name, long count, long granularity, boolean frozen) {
		this.name = name;
		this.count = count;
		this.granularity = granularity;
		this.frozen = frozen;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("name");
		names.add("count");
		names.add("granularity");
		names.add("frozen");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("name".equals(name))
			return name;
		if ("count".equals(name))
			return count;
		if ("granularity".equals(name))
			return granularity;
		if ("frozen".equals(name))
			return frozen;
		return super.getFieldByName(name);
	}
}
