package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=change-vnc-password, returns=null, data={password=str}}</pre>
 */
// QApiCommandDescriptor{name=change-vnc-password, returns=null, data={password=str}}
public class ChangeVncPasswordCommand extends QApiCommand<ChangeVncPasswordCommand.Arguments, ChangeVncPasswordCommand.Response> {
	/** Compound arguments to a ChangeVncPasswordCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("password")
		@Nonnull
		public java.lang.String password;

		public Arguments() {
		}

		public Arguments(java.lang.String password) {
			this.password = password;
		}
	}

	/** Response to a ChangeVncPasswordCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new ChangeVncPasswordCommand. */
	public ChangeVncPasswordCommand(@Nonnull ChangeVncPasswordCommand.Arguments argument) {
		super("change-vnc-password", Response.class, argument);
	}

	/** Constructs a new ChangeVncPasswordCommand. */
	public ChangeVncPasswordCommand(java.lang.String password) {
		this(new Arguments(password));
	}
}
