package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiUnionDescriptor{name=ChardevBackend, discrinimator=null, data={file=ChardevFile, serial=ChardevHostdev, parallel=ChardevHostdev, pipe=ChardevHostdev, socket=ChardevSocket, udp=ChardevUdp, pty=ChardevDummy, null=ChardevDummy, mux=ChardevMux, msmouse=ChardevDummy, braille=ChardevDummy, testdev=ChardevDummy, stdio=ChardevStdio, console=ChardevDummy, spicevmc=ChardevSpiceChannel, spiceport=ChardevSpicePort, vc=ChardevVC, ringbuf=ChardevRingbuf, memory=ChardevRingbuf}, innerTypes=null, fields=null, discriminatorField=null}</pre>
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class ChardevBackend extends QApiType implements QApiUnion {
	public static enum Discriminator {
		file,
		serial,
		parallel,
		pipe,
		socket,
		udp,
		pty,
		_null,
		mux,
		msmouse,
		braille,
		testdev,
		stdio,
		console,
		spicevmc,
		spiceport,
		vc,
		ringbuf,
		memory,
		__NONE;
	}

	@Nonnull
	@JsonProperty("type")
	public Discriminator type;

	@Nonnull
	public final Discriminator getType() {
		return type;
	}

	// union {
	@JsonProperty("file")
	@JsonUnwrapped
	@CheckForNull
	public ChardevFile file;
	@JsonProperty("serial")
	@JsonUnwrapped
	@CheckForNull
	public ChardevHostdev serial;
	@JsonProperty("parallel")
	@JsonUnwrapped
	@CheckForNull
	public ChardevHostdev parallel;
	@JsonProperty("pipe")
	@JsonUnwrapped
	@CheckForNull
	public ChardevHostdev pipe;
	@JsonProperty("socket")
	@JsonUnwrapped
	@CheckForNull
	public ChardevSocket socket;
	@JsonProperty("udp")
	@JsonUnwrapped
	@CheckForNull
	public ChardevUdp udp;
	@JsonProperty("pty")
	@JsonUnwrapped
	@CheckForNull
	public ChardevDummy pty;
	@JsonProperty("null")
	@JsonUnwrapped
	@CheckForNull
	public ChardevDummy _null;
	@JsonProperty("mux")
	@JsonUnwrapped
	@CheckForNull
	public ChardevMux mux;
	@JsonProperty("msmouse")
	@JsonUnwrapped
	@CheckForNull
	public ChardevDummy msmouse;
	@JsonProperty("braille")
	@JsonUnwrapped
	@CheckForNull
	public ChardevDummy braille;
	@JsonProperty("testdev")
	@JsonUnwrapped
	@CheckForNull
	public ChardevDummy testdev;
	@JsonProperty("stdio")
	@JsonUnwrapped
	@CheckForNull
	public ChardevStdio stdio;
	@JsonProperty("console")
	@JsonUnwrapped
	@CheckForNull
	public ChardevDummy console;
	@JsonProperty("spicevmc")
	@JsonUnwrapped
	@CheckForNull
	public ChardevSpiceChannel spicevmc;
	@JsonProperty("spiceport")
	@JsonUnwrapped
	@CheckForNull
	public ChardevSpicePort spiceport;
	@JsonProperty("vc")
	@JsonUnwrapped
	@CheckForNull
	public ChardevVC vc;
	@JsonProperty("ringbuf")
	@JsonUnwrapped
	@CheckForNull
	public ChardevRingbuf ringbuf;
	@JsonProperty("memory")
	@JsonUnwrapped
	@CheckForNull
	public ChardevRingbuf memory;
	// }

	@Nonnull
	public static ChardevBackend file(@Nonnull ChardevFile file) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.file;
		self.file = file;
		return self;
	}

	@Nonnull
	public static ChardevBackend serial(@Nonnull ChardevHostdev serial) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.serial;
		self.serial = serial;
		return self;
	}

	@Nonnull
	public static ChardevBackend parallel(@Nonnull ChardevHostdev parallel) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.parallel;
		self.parallel = parallel;
		return self;
	}

	@Nonnull
	public static ChardevBackend pipe(@Nonnull ChardevHostdev pipe) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.pipe;
		self.pipe = pipe;
		return self;
	}

	@Nonnull
	public static ChardevBackend socket(@Nonnull ChardevSocket socket) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.socket;
		self.socket = socket;
		return self;
	}

	@Nonnull
	public static ChardevBackend udp(@Nonnull ChardevUdp udp) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.udp;
		self.udp = udp;
		return self;
	}

	@Nonnull
	public static ChardevBackend pty(@Nonnull ChardevDummy pty) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.pty;
		self.pty = pty;
		return self;
	}

	@Nonnull
	public static ChardevBackend _null(@Nonnull ChardevDummy _null) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator._null;
		self._null = _null;
		return self;
	}

	@Nonnull
	public static ChardevBackend mux(@Nonnull ChardevMux mux) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.mux;
		self.mux = mux;
		return self;
	}

	@Nonnull
	public static ChardevBackend msmouse(@Nonnull ChardevDummy msmouse) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.msmouse;
		self.msmouse = msmouse;
		return self;
	}

	@Nonnull
	public static ChardevBackend braille(@Nonnull ChardevDummy braille) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.braille;
		self.braille = braille;
		return self;
	}

	@Nonnull
	public static ChardevBackend testdev(@Nonnull ChardevDummy testdev) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.testdev;
		self.testdev = testdev;
		return self;
	}

	@Nonnull
	public static ChardevBackend stdio(@Nonnull ChardevStdio stdio) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.stdio;
		self.stdio = stdio;
		return self;
	}

	@Nonnull
	public static ChardevBackend console(@Nonnull ChardevDummy console) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.console;
		self.console = console;
		return self;
	}

	@Nonnull
	public static ChardevBackend spicevmc(@Nonnull ChardevSpiceChannel spicevmc) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.spicevmc;
		self.spicevmc = spicevmc;
		return self;
	}

	@Nonnull
	public static ChardevBackend spiceport(@Nonnull ChardevSpicePort spiceport) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.spiceport;
		self.spiceport = spiceport;
		return self;
	}

	@Nonnull
	public static ChardevBackend vc(@Nonnull ChardevVC vc) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.vc;
		self.vc = vc;
		return self;
	}

	@Nonnull
	public static ChardevBackend ringbuf(@Nonnull ChardevRingbuf ringbuf) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.ringbuf;
		self.ringbuf = ringbuf;
		return self;
	}

	@Nonnull
	public static ChardevBackend memory(@Nonnull ChardevRingbuf memory) {
		ChardevBackend self = new ChardevBackend();
		self.type = Discriminator.memory;
		self.memory = memory;
		return self;
	}

	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("file");
		names.add("serial");
		names.add("parallel");
		names.add("pipe");
		names.add("socket");
		names.add("udp");
		names.add("pty");
		names.add("null");
		names.add("mux");
		names.add("msmouse");
		names.add("braille");
		names.add("testdev");
		names.add("stdio");
		names.add("console");
		names.add("spicevmc");
		names.add("spiceport");
		names.add("vc");
		names.add("ringbuf");
		names.add("memory");
		return names;
	}

	@JsonIgnore
	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("file".equals(name))
			return file;
		if ("serial".equals(name))
			return serial;
		if ("parallel".equals(name))
			return parallel;
		if ("pipe".equals(name))
			return pipe;
		if ("socket".equals(name))
			return socket;
		if ("udp".equals(name))
			return udp;
		if ("pty".equals(name))
			return pty;
		if ("null".equals(name))
			return _null;
		if ("mux".equals(name))
			return mux;
		if ("msmouse".equals(name))
			return msmouse;
		if ("braille".equals(name))
			return braille;
		if ("testdev".equals(name))
			return testdev;
		if ("stdio".equals(name))
			return stdio;
		if ("console".equals(name))
			return console;
		if ("spicevmc".equals(name))
			return spicevmc;
		if ("spiceport".equals(name))
			return spiceport;
		if ("vc".equals(name))
			return vc;
		if ("ringbuf".equals(name))
			return ringbuf;
		if ("memory".equals(name))
			return memory;
		return super.getFieldByName(name);
	}

	@Override
	@JsonIgnore
	public boolean isValidUnion() {
		int count = 0;
		if (file != null)
			count++;
		if (serial != null)
			count++;
		if (parallel != null)
			count++;
		if (pipe != null)
			count++;
		if (socket != null)
			count++;
		if (udp != null)
			count++;
		if (pty != null)
			count++;
		if (_null != null)
			count++;
		if (mux != null)
			count++;
		if (msmouse != null)
			count++;
		if (braille != null)
			count++;
		if (testdev != null)
			count++;
		if (stdio != null)
			count++;
		if (console != null)
			count++;
		if (spicevmc != null)
			count++;
		if (spiceport != null)
			count++;
		if (vc != null)
			count++;
		if (ringbuf != null)
			count++;
		if (memory != null)
			count++;
		return (count == 1);
	}
}
