package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEnumDescriptor{name=COLOMessage, data=[checkpoint-ready, checkpoint-request, checkpoint-reply, vmstate-send, vmstate-size, vmstate-received, vmstate-loaded], fields=null}</pre>
 */
// QApiEnumDescriptor{name=COLOMessage, data=[checkpoint-ready, checkpoint-request, checkpoint-reply, vmstate-send, vmstate-size, vmstate-received, vmstate-loaded], fields=null}
public enum COLOMessage {
	checkpoint_ready("checkpoint-ready"),
	checkpoint_request("checkpoint-request"),
	checkpoint_reply("checkpoint-reply"),
	vmstate_send("vmstate-send"),
	vmstate_size("vmstate-size"),
	vmstate_received("vmstate-received"),
	vmstate_loaded("vmstate-loaded"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ COLOMessage(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
