package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=COMMAND_DROPPED, data={id=any, reason=CommandDropReason}}</pre>
 */
// QApiEventDescriptor{name=COMMAND_DROPPED, data={id=any, reason=CommandDropReason}}
public class CommandDroppedEvent extends QApiEvent {

	public static class Data {
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("id")
		@Nonnull
		public java.lang.Object id;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("reason")
		@Nonnull
		public CommandDropReason reason;
	}

	@JsonProperty("data")
	public Data data;
}
