package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiStructDescriptor{name=DisplayGTK, data={*grab-on-hover=bool}, innerTypes=null, fields=null, base=null}</pre>
 */
// QApiStructDescriptor{name=DisplayGTK, data={*grab-on-hover=bool}, innerTypes=null, fields=null, base=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class DisplayGTK extends QApiType {

	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("grab-on-hover")
	@CheckForNull
	public java.lang.Boolean grabOnHover;

	@Nonnull
	public DisplayGTK withGrabOnHover(java.lang.Boolean value) {
		this.grabOnHover = value;
		return this;
	}

	public DisplayGTK() {
	}

	public DisplayGTK(java.lang.Boolean grabOnHover) {
		this.grabOnHover = grabOnHover;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("grab-on-hover");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("grab-on-hover".equals(name))
			return grabOnHover;
		return super.getFieldByName(name);
	}
}
