package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiStructDescriptor{name=DumpGuestMemoryCapability, data={formats=[DumpGuestMemoryFormat]}, innerTypes=null, fields=null, base=null}</pre>
 */
// QApiStructDescriptor{name=DumpGuestMemoryCapability, data={formats=[DumpGuestMemoryFormat]}, innerTypes=null, fields=null, base=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class DumpGuestMemoryCapability extends QApiType {

	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("formats")
	@Nonnull
	public java.util.List<DumpGuestMemoryFormat> formats;

	@Nonnull
	public DumpGuestMemoryCapability withFormats(java.util.List<DumpGuestMemoryFormat> value) {
		this.formats = value;
		return this;
	}

	public DumpGuestMemoryCapability() {
	}

	public DumpGuestMemoryCapability(java.util.List<DumpGuestMemoryFormat> formats) {
		this.formats = formats;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("formats");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("formats".equals(name))
			return formats;
		return super.getFieldByName(name);
	}
}
