package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEnumDescriptor{name=InputButton, data=[Left, Middle, Right, WheelUp, WheelDown], fields=null}</pre>
 */
// QApiEnumDescriptor{name=InputButton, data=[Left, Middle, Right, WheelUp, WheelDown], fields=null}
public enum InputButton {
	Left("Left"),
	Middle("Middle"),
	Right("Right"),
	WheelUp("WheelUp"),
	WheelDown("WheelDown"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ InputButton(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
