package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEnumDescriptor{name=MigrationParameter, data=[compress-level, compress-threads, decompress-threads, cpu-throttle-initial, cpu-throttle-increment, tls-creds, tls-hostname, max-bandwidth, downtime-limit, x-checkpoint-delay, block-incremental, x-multifd-channels, x-multifd-page-count, xbzrle-cache-size], fields=null}</pre>
 */
// QApiEnumDescriptor{name=MigrationParameter, data=[compress-level, compress-threads, decompress-threads, cpu-throttle-initial, cpu-throttle-increment, tls-creds, tls-hostname, max-bandwidth, downtime-limit, x-checkpoint-delay, block-incremental, x-multifd-channels, x-multifd-page-count, xbzrle-cache-size], fields=null}
public enum MigrationParameter {
	compress_level("compress-level"),
	compress_threads("compress-threads"),
	decompress_threads("decompress-threads"),
	cpu_throttle_initial("cpu-throttle-initial"),
	cpu_throttle_increment("cpu-throttle-increment"),
	tls_creds("tls-creds"),
	tls_hostname("tls-hostname"),
	max_bandwidth("max-bandwidth"),
	downtime_limit("downtime-limit"),
	x_checkpoint_delay("x-checkpoint-delay"),
	block_incremental("block-incremental"),
	x_multifd_channels("x-multifd-channels"),
	x_multifd_page_count("x-multifd-page-count"),
	xbzrle_cache_size("xbzrle-cache-size"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ MigrationParameter(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
