package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=migrate_set_speed, returns=null, data={value=int}}</pre>
 */
// QApiCommandDescriptor{name=migrate_set_speed, returns=null, data={value=int}}
public class MigrateSetSpeedCommand extends QApiCommand<MigrateSetSpeedCommand.Arguments, MigrateSetSpeedCommand.Response> {
	/** Compound arguments to a MigrateSetSpeedCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("value")
		@Nonnull
		public long value;

		public Arguments() {
		}

		public Arguments(long value) {
			this.value = value;
		}
	}

	/** Response to a MigrateSetSpeedCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new MigrateSetSpeedCommand. */
	public MigrateSetSpeedCommand(@Nonnull MigrateSetSpeedCommand.Arguments argument) {
		super("migrate_set_speed", Response.class, argument);
	}

	/** Constructs a new MigrateSetSpeedCommand. */
	public MigrateSetSpeedCommand(long value) {
		this(new Arguments(value));
	}
}
