package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEnumDescriptor{name=MigrationCapability, data=[xbzrle, rdma-pin-all, auto-converge, zero-blocks, compress, events, postcopy-ram, x-colo, release-ram, block, return-path, pause-before-switchover, x-multifd, dirty-bitmaps], fields=null}</pre>
 */
// QApiEnumDescriptor{name=MigrationCapability, data=[xbzrle, rdma-pin-all, auto-converge, zero-blocks, compress, events, postcopy-ram, x-colo, release-ram, block, return-path, pause-before-switchover, x-multifd, dirty-bitmaps], fields=null}
public enum MigrationCapability {
	xbzrle("xbzrle"),
	rdma_pin_all("rdma-pin-all"),
	auto_converge("auto-converge"),
	zero_blocks("zero-blocks"),
	compress("compress"),
	events("events"),
	postcopy_ram("postcopy-ram"),
	x_colo("x-colo"),
	release_ram("release-ram"),
	block("block"),
	return_path("return-path"),
	pause_before_switchover("pause-before-switchover"),
	x_multifd("x-multifd"),
	dirty_bitmaps("dirty-bitmaps"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ MigrationCapability(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
