package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiEnumDescriptor{name=MigrationCapability, data=[xbzrle, rdma-pin-all, auto-converge, zero-blocks], fields=null}</pre></p>
 */
// QApiEnumDescriptor{name=MigrationCapability, data=[xbzrle, rdma-pin-all, auto-converge, zero-blocks], fields=null}
public enum MigrationCapability {
	// @JsonProperty("xbzrle")
	xbzrle("xbzrle"),
	// @JsonProperty("rdma-pin-all")
	rdma_pin_all("rdma-pin-all"),
	// @JsonProperty("auto-converge")
	auto_converge("auto-converge"),
	// @JsonProperty("zero-blocks")
	zero_blocks("zero-blocks"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ MigrationCapability(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
