package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEnumDescriptor{name=NbdServerRemoveMode, data=[safe, hard], fields=null}</pre>
 */
// QApiEnumDescriptor{name=NbdServerRemoveMode, data=[safe, hard], fields=null}
public enum NbdServerRemoveMode {
	safe("safe"),
	hard("hard"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ NbdServerRemoveMode(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
