package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiUnionDescriptor{name=NetClientOptions, data={none=NetdevNoneOptions, nic=NetLegacyNicOptions, user=NetdevUserOptions, tap=NetdevTapOptions, l2tpv3=NetdevL2TPv3Options, socket=NetdevSocketOptions, vde=NetdevVdeOptions, dump=NetdevDumpOptions, bridge=NetdevBridgeOptions, hubport=NetdevHubPortOptions, netmap=NetdevNetmapOptions, vhost-user=NetdevVhostUserOptions}, innerTypes=null, fields=null, discriminatorField=null}</pre></p>
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class NetClientOptions extends QApiType implements QApiUnion {
	public static enum Discriminator {
		none,
		nic,
		user,
		tap,
		l2tpv3,
		socket,
		vde,
		dump,
		bridge,
		hubport,
		netmap,
		vhostUser,
		__NONE;
	}

	@Nonnull
	@JsonProperty("type")
	public Discriminator type;

	@Nonnull
	public final Discriminator getType() {
		return type;
	}

	// union {
	@JsonProperty("none")
	@JsonUnwrapped
	@CheckForNull
	public NetdevNoneOptions none;
	@JsonProperty("nic")
	@JsonUnwrapped
	@CheckForNull
	public NetLegacyNicOptions nic;
	@JsonProperty("user")
	@JsonUnwrapped
	@CheckForNull
	public NetdevUserOptions user;
	@JsonProperty("tap")
	@JsonUnwrapped
	@CheckForNull
	public NetdevTapOptions tap;
	@JsonProperty("l2tpv3")
	@JsonUnwrapped
	@CheckForNull
	public NetdevL2TPv3Options l2tpv3;
	@JsonProperty("socket")
	@JsonUnwrapped
	@CheckForNull
	public NetdevSocketOptions socket;
	@JsonProperty("vde")
	@JsonUnwrapped
	@CheckForNull
	public NetdevVdeOptions vde;
	@JsonProperty("dump")
	@JsonUnwrapped
	@CheckForNull
	public NetdevDumpOptions dump;
	@JsonProperty("bridge")
	@JsonUnwrapped
	@CheckForNull
	public NetdevBridgeOptions bridge;
	@JsonProperty("hubport")
	@JsonUnwrapped
	@CheckForNull
	public NetdevHubPortOptions hubport;
	@JsonProperty("netmap")
	@JsonUnwrapped
	@CheckForNull
	public NetdevNetmapOptions netmap;
	@JsonProperty("vhost-user")
	@JsonUnwrapped
	@CheckForNull
	public NetdevVhostUserOptions vhostUser;
	// }

	@Nonnull
	public static NetClientOptions none(@Nonnull NetdevNoneOptions none) {
		NetClientOptions self = new NetClientOptions();
		self.type = Discriminator.none;
		self.none = none;
		return self;
	}

	@Nonnull
	public static NetClientOptions nic(@Nonnull NetLegacyNicOptions nic) {
		NetClientOptions self = new NetClientOptions();
		self.type = Discriminator.nic;
		self.nic = nic;
		return self;
	}

	@Nonnull
	public static NetClientOptions user(@Nonnull NetdevUserOptions user) {
		NetClientOptions self = new NetClientOptions();
		self.type = Discriminator.user;
		self.user = user;
		return self;
	}

	@Nonnull
	public static NetClientOptions tap(@Nonnull NetdevTapOptions tap) {
		NetClientOptions self = new NetClientOptions();
		self.type = Discriminator.tap;
		self.tap = tap;
		return self;
	}

	@Nonnull
	public static NetClientOptions l2tpv3(@Nonnull NetdevL2TPv3Options l2tpv3) {
		NetClientOptions self = new NetClientOptions();
		self.type = Discriminator.l2tpv3;
		self.l2tpv3 = l2tpv3;
		return self;
	}

	@Nonnull
	public static NetClientOptions socket(@Nonnull NetdevSocketOptions socket) {
		NetClientOptions self = new NetClientOptions();
		self.type = Discriminator.socket;
		self.socket = socket;
		return self;
	}

	@Nonnull
	public static NetClientOptions vde(@Nonnull NetdevVdeOptions vde) {
		NetClientOptions self = new NetClientOptions();
		self.type = Discriminator.vde;
		self.vde = vde;
		return self;
	}

	@Nonnull
	public static NetClientOptions dump(@Nonnull NetdevDumpOptions dump) {
		NetClientOptions self = new NetClientOptions();
		self.type = Discriminator.dump;
		self.dump = dump;
		return self;
	}

	@Nonnull
	public static NetClientOptions bridge(@Nonnull NetdevBridgeOptions bridge) {
		NetClientOptions self = new NetClientOptions();
		self.type = Discriminator.bridge;
		self.bridge = bridge;
		return self;
	}

	@Nonnull
	public static NetClientOptions hubport(@Nonnull NetdevHubPortOptions hubport) {
		NetClientOptions self = new NetClientOptions();
		self.type = Discriminator.hubport;
		self.hubport = hubport;
		return self;
	}

	@Nonnull
	public static NetClientOptions netmap(@Nonnull NetdevNetmapOptions netmap) {
		NetClientOptions self = new NetClientOptions();
		self.type = Discriminator.netmap;
		self.netmap = netmap;
		return self;
	}

	@Nonnull
	public static NetClientOptions vhostUser(@Nonnull NetdevVhostUserOptions vhostUser) {
		NetClientOptions self = new NetClientOptions();
		self.type = Discriminator.vhostUser;
		self.vhostUser = vhostUser;
		return self;
	}

	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("none");
		names.add("nic");
		names.add("user");
		names.add("tap");
		names.add("l2tpv3");
		names.add("socket");
		names.add("vde");
		names.add("dump");
		names.add("bridge");
		names.add("hubport");
		names.add("netmap");
		names.add("vhost-user");
		return names;
	}

	@JsonIgnore
	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("none".equals(name))
			return none;
		if ("nic".equals(name))
			return nic;
		if ("user".equals(name))
			return user;
		if ("tap".equals(name))
			return tap;
		if ("l2tpv3".equals(name))
			return l2tpv3;
		if ("socket".equals(name))
			return socket;
		if ("vde".equals(name))
			return vde;
		if ("dump".equals(name))
			return dump;
		if ("bridge".equals(name))
			return bridge;
		if ("hubport".equals(name))
			return hubport;
		if ("netmap".equals(name))
			return netmap;
		if ("vhost-user".equals(name))
			return vhostUser;
		return super.getFieldByName(name);
	}

	@Override
	@JsonIgnore
	public boolean isValidUnion() {
		int count = 0;
		if (none != null)
			count++;
		if (nic != null)
			count++;
		if (user != null)
			count++;
		if (tap != null)
			count++;
		if (l2tpv3 != null)
			count++;
		if (socket != null)
			count++;
		if (vde != null)
			count++;
		if (dump != null)
			count++;
		if (bridge != null)
			count++;
		if (hubport != null)
			count++;
		if (netmap != null)
			count++;
		if (vhostUser != null)
			count++;
		return (count == 1);
	}
}
