package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiTypeDescriptor{name=PciBridgeInfo, data={bus=PciBusInfo, *devices=[PciDeviceInfo]}, innerTypes=null}</pre>
 */
// QApiTypeDescriptor{name=PciBridgeInfo, data={bus=PciBusInfo, *devices=[PciDeviceInfo]}, innerTypes=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class PciBridgeInfo extends QApiType {

	@JsonProperty("bus")
	@Nonnull
	public PciBusInfo bus;
	@JsonProperty("devices")
	@CheckForNull
	public java.util.List<PciDeviceInfo> devices;

	@Nonnull
	public PciBridgeInfo withBus(PciBusInfo value) {
		this.bus = value;
		return this;
	}

	@Nonnull
	public PciBridgeInfo withDevices(java.util.List<PciDeviceInfo> value) {
		this.devices = value;
		return this;
	}

	public PciBridgeInfo() {
	}

	public PciBridgeInfo(PciBusInfo bus, java.util.List<PciDeviceInfo> devices) {
		this.bus = bus;
		this.devices = devices;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("bus");
		names.add("devices");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("bus".equals(name))
			return bus;
		if ("devices".equals(name))
			return devices;
		return super.getFieldByName(name);
	}
}
