package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiStructDescriptor{name=PciDeviceId, data={device=int, vendor=int}, innerTypes=null, fields=null, base=null}</pre>
 */
// QApiStructDescriptor{name=PciDeviceId, data={device=int, vendor=int}, innerTypes=null, fields=null, base=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class PciDeviceId extends QApiType {

	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("device")
	@Nonnull
	public long device;
	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("vendor")
	@Nonnull
	public long vendor;

	@Nonnull
	public PciDeviceId withDevice(long value) {
		this.device = value;
		return this;
	}

	@Nonnull
	public PciDeviceId withVendor(long value) {
		this.vendor = value;
		return this;
	}

	public PciDeviceId() {
	}

	public PciDeviceId(long device, long vendor) {
		this.device = device;
		this.vendor = vendor;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("device");
		names.add("vendor");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("device".equals(name))
			return device;
		if ("vendor".equals(name))
			return vendor;
		return super.getFieldByName(name);
	}
}
