package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiTypeDescriptor{name=PciDeviceClass, data={*desc=str, class=int}, innerTypes=null}</pre>
 */
// QApiTypeDescriptor{name=PciDeviceClass, data={*desc=str, class=int}, innerTypes=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class PciDeviceClass extends QApiType {

	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("desc")
	@CheckForNull
	public java.lang.String desc;
	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("class")
	@Nonnull
	public long _class;

	@Nonnull
	public PciDeviceClass withDesc(java.lang.String value) {
		this.desc = value;
		return this;
	}

	@Nonnull
	public PciDeviceClass with_class(long value) {
		this._class = value;
		return this;
	}

	public PciDeviceClass() {
	}

	public PciDeviceClass(java.lang.String desc, long _class) {
		this.desc = desc;
		this._class = _class;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("desc");
		names.add("class");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("desc".equals(name))
			return desc;
		if ("class".equals(name))
			return _class;
		return super.getFieldByName(name);
	}
}
