package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEnumDescriptor{name=QCryptoTLSCredsEndpoint, data=[client, server], fields=null}</pre>
 */
// QApiEnumDescriptor{name=QCryptoTLSCredsEndpoint, data=[client, server], fields=null}
public enum QCryptoTLSCredsEndpoint {
	client("client"),
	server("server"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ QCryptoTLSCredsEndpoint(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
