package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEnumDescriptor{name=QCryptoHashAlgorithm, data=[md5, sha1, sha224, sha256, sha384, sha512, ripemd160], fields=null}</pre>
 */
// QApiEnumDescriptor{name=QCryptoHashAlgorithm, data=[md5, sha1, sha224, sha256, sha384, sha512, ripemd160], fields=null}
public enum QCryptoHashAlgorithm {
	md5("md5"),
	sha1("sha1"),
	sha224("sha224"),
	sha256("sha256"),
	sha384("sha384"),
	sha512("sha512"),
	ripemd160("ripemd160"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ QCryptoHashAlgorithm(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
