package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEnumDescriptor{name=QCryptoCipherAlgorithm, data=[aes-128, aes-192, aes-256, des-rfb, 3des, cast5-128, serpent-128, serpent-192, serpent-256, twofish-128, twofish-192, twofish-256], fields=null}</pre>
 */
// QApiEnumDescriptor{name=QCryptoCipherAlgorithm, data=[aes-128, aes-192, aes-256, des-rfb, 3des, cast5-128, serpent-128, serpent-192, serpent-256, twofish-128, twofish-192, twofish-256], fields=null}
public enum QCryptoCipherAlgorithm {
	aes_128("aes-128"),
	aes_192("aes-192"),
	aes_256("aes-256"),
	des_rfb("des-rfb"),
	_3des("3des"),
	cast5_128("cast5-128"),
	serpent_128("serpent-128"),
	serpent_192("serpent-192"),
	serpent_256("serpent-256"),
	twofish_128("twofish-128"),
	twofish_192("twofish-192"),
	twofish_256("twofish-256"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ QCryptoCipherAlgorithm(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
