package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=qmp_capabilities, returns=null, data=null}</pre>
 */
// QApiCommandDescriptor{name=qmp_capabilities, returns=null, data=null}
public class QmpCapabilitiesCommand extends QApiCommand<java.lang.Void, QmpCapabilitiesCommand.Response> {

	/** Response to a QmpCapabilitiesCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new QmpCapabilitiesCommand. */
	public QmpCapabilitiesCommand() {
		super("qmp_capabilities", Response.class, null);
	}

}
