package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=qom-list, returns=[ObjectPropertyInfo], data={path=str}}</pre>
 */
// QApiCommandDescriptor{name=qom-list, returns=[ObjectPropertyInfo], data={path=str}}
public class QomListCommand extends QApiCommand<QomListCommand.Arguments, QomListCommand.Response> {
	/** Compound arguments to a QomListCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		@JsonProperty("path")
		@Nonnull
		public java.lang.String path;

		public Arguments() {
		}

		public Arguments(java.lang.String path) {
			this.path = path;
		}
	}

	/** Response to a QomListCommand. */
	public static class Response extends QApiResponse<java.util.List<ObjectPropertyInfo>> {
	}

	/** Constructs a new QomListCommand. */
	public QomListCommand(@Nonnull QomListCommand.Arguments argument) {
		super("qom-list", Response.class, argument);
	}

	/** Constructs a new QomListCommand. */
	public QomListCommand(java.lang.String path) {
		this(new Arguments(path));
	}
}
