package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=qom-list-types, returns=[ObjectTypeInfo], data={*implements=str, *abstract=bool}}</pre>
 */
// QApiCommandDescriptor{name=qom-list-types, returns=[ObjectTypeInfo], data={*implements=str, *abstract=bool}}
public class QomListTypesCommand extends QApiCommand<QomListTypesCommand.Arguments, QomListTypesCommand.Response> {
	/** Compound arguments to a QomListTypesCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("implements")
		@CheckForNull
		public java.lang.String _implements;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("abstract")
		@CheckForNull
		public java.lang.Boolean _abstract;

		public Arguments() {
		}

		public Arguments(java.lang.String _implements, java.lang.Boolean _abstract) {
			this._implements = _implements;
			this._abstract = _abstract;
		}
	}

	/** Response to a QomListTypesCommand. */
	public static class Response extends QApiResponse<java.util.List<ObjectTypeInfo>> {
	}

	/** Constructs a new QomListTypesCommand. */
	public QomListTypesCommand(@Nonnull QomListTypesCommand.Arguments argument) {
		super("qom-list-types", Response.class, argument);
	}

	/** Constructs a new QomListTypesCommand. */
	public QomListTypesCommand(java.lang.String _implements, java.lang.Boolean _abstract) {
		this(new Arguments(_implements, _abstract));
	}
}
