package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-status, returns=StatusInfo, data=null}</pre>
 */
// QApiCommandDescriptor{name=query-status, returns=StatusInfo, data=null}
public class QueryStatusCommand extends QApiCommand<java.lang.Void, QueryStatusCommand.Response> {

	/** Response to a QueryStatusCommand. */
	public static class Response extends QApiResponse<StatusInfo> {
	}

	/** Constructs a new QueryStatusCommand. */
	public QueryStatusCommand() {
		super("query-status", Response.class, null);
	}

}
