package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-rocker, returns=RockerSwitch, data={name=str}}</pre>
 */
// QApiCommandDescriptor{name=query-rocker, returns=RockerSwitch, data={name=str}}
public class QueryRockerCommand extends QApiCommand<QueryRockerCommand.Arguments, QueryRockerCommand.Response> {
	/** Compound arguments to a QueryRockerCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("name")
		@Nonnull
		public java.lang.String name;

		public Arguments() {
		}

		public Arguments(java.lang.String name) {
			this.name = name;
		}
	}

	/** Response to a QueryRockerCommand. */
	public static class Response extends QApiResponse<RockerSwitch> {
	}

	/** Constructs a new QueryRockerCommand. */
	public QueryRockerCommand(@Nonnull QueryRockerCommand.Arguments argument) {
		super("query-rocker", Response.class, argument);
	}

	/** Constructs a new QueryRockerCommand. */
	public QueryRockerCommand(java.lang.String name) {
		this(new Arguments(name));
	}
}
