package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-rocker-of-dpa-groups, returns=[RockerOfDpaGroup], data={name=str, *type=uint8}}</pre>
 */
// QApiCommandDescriptor{name=query-rocker-of-dpa-groups, returns=[RockerOfDpaGroup], data={name=str, *type=uint8}}
public class QueryRockerOfDpaGroupsCommand extends QApiCommand<QueryRockerOfDpaGroupsCommand.Arguments, QueryRockerOfDpaGroupsCommand.Response> {
	/** Compound arguments to a QueryRockerOfDpaGroupsCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("name")
		@Nonnull
		public java.lang.String name;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("type")
		@CheckForNull
		public char type;

		public Arguments() {
		}

		public Arguments(java.lang.String name, char type) {
			this.name = name;
			this.type = type;
		}
	}

	/** Response to a QueryRockerOfDpaGroupsCommand. */
	public static class Response extends QApiResponse<java.util.List<RockerOfDpaGroup>> {
	}

	/** Constructs a new QueryRockerOfDpaGroupsCommand. */
	public QueryRockerOfDpaGroupsCommand(@Nonnull QueryRockerOfDpaGroupsCommand.Arguments argument) {
		super("query-rocker-of-dpa-groups", Response.class, argument);
	}

	/** Constructs a new QueryRockerOfDpaGroupsCommand. */
	public QueryRockerOfDpaGroupsCommand(java.lang.String name, char type) {
		this(new Arguments(name, type));
	}
}
