package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiEventDescriptor{name=QUORUM_REPORT_BAD, data={*error=str, node-name=str, sector-num=int, sectors-count=int}}</pre></p>
 */
// QApiEventDescriptor{name=QUORUM_REPORT_BAD, data={*error=str, node-name=str, sector-num=int, sectors-count=int}}
public class QuorumReportBadEvent extends QApiEvent {
	@JsonProperty("error")
	@CheckForNull
	public java.lang.String error;
	@JsonProperty("node-name")
	@Nonnull
	public java.lang.String nodeName;
	@JsonProperty("sector-num")
	@Nonnull
	public long sectorNum;
	@JsonProperty("sectors-count")
	@Nonnull
	public long sectorsCount;
}
