package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEnumDescriptor{name=RunState, data=[debug, inmigrate, internal-error, io-error, paused, postmigrate, prelaunch, finish-migrate, restore-vm, running, save-vm, shutdown, suspended, watchdog, guest-panicked, colo], fields=null}</pre>
 */
// QApiEnumDescriptor{name=RunState, data=[debug, inmigrate, internal-error, io-error, paused, postmigrate, prelaunch, finish-migrate, restore-vm, running, save-vm, shutdown, suspended, watchdog, guest-panicked, colo], fields=null}
public enum RunState {
	debug("debug"),
	inmigrate("inmigrate"),
	internal_error("internal-error"),
	io_error("io-error"),
	paused("paused"),
	postmigrate("postmigrate"),
	prelaunch("prelaunch"),
	finish_migrate("finish-migrate"),
	restore_vm("restore-vm"),
	running("running"),
	save_vm("save-vm"),
	shutdown("shutdown"),
	suspended("suspended"),
	watchdog("watchdog"),
	guest_panicked("guest-panicked"),
	colo("colo"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ RunState(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
