package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEnumDescriptor{name=RxState, data=[normal, none, all], fields=null}</pre>
 */
// QApiEnumDescriptor{name=RxState, data=[normal, none, all], fields=null}
public enum RxState {
	normal("normal"),
	none("none"),
	all("all"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ RxState(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
