package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiTypeDescriptor{name=SchemaInfoCommand, data={arg-type=str, ret-type=str}, innerTypes=null}</pre>
 */
// QApiTypeDescriptor{name=SchemaInfoCommand, data={arg-type=str, ret-type=str}, innerTypes=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class SchemaInfoCommand extends QApiType {

	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("arg-type")
	@Nonnull
	public java.lang.String argType;
	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("ret-type")
	@Nonnull
	public java.lang.String retType;

	@Nonnull
	public SchemaInfoCommand withArgType(java.lang.String value) {
		this.argType = value;
		return this;
	}

	@Nonnull
	public SchemaInfoCommand withRetType(java.lang.String value) {
		this.retType = value;
		return this;
	}

	public SchemaInfoCommand() {
	}

	public SchemaInfoCommand(java.lang.String argType, java.lang.String retType) {
		this.argType = argType;
		this.retType = retType;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("arg-type");
		names.add("ret-type");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("arg-type".equals(name))
			return argType;
		if ("ret-type".equals(name))
			return retType;
		return super.getFieldByName(name);
	}
}
