package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=screendump, returns=null, data={filename=str}}</pre>
 */
// QApiCommandDescriptor{name=screendump, returns=null, data={filename=str}}
public class ScreendumpCommand extends QApiCommand<ScreendumpCommand.Arguments, ScreendumpCommand.Response> {
	/** Compound arguments to a ScreendumpCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		@JsonProperty("filename")
		@Nonnull
		public java.lang.String filename;

		public Arguments() {
		}

		public Arguments(java.lang.String filename) {
			this.filename = filename;
		}
	}

	/** Response to a ScreendumpCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new ScreendumpCommand. */
	public ScreendumpCommand(@Nonnull ScreendumpCommand.Arguments argument) {
		super("screendump", Response.class, argument);
	}

	/** Constructs a new ScreendumpCommand. */
	public ScreendumpCommand(java.lang.String filename) {
		this(new Arguments(filename));
	}
}
