package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=screendump, returns=null, data={filename=str, *device=str, *head=int}}</pre>
 */
// QApiCommandDescriptor{name=screendump, returns=null, data={filename=str, *device=str, *head=int}}
public class ScreendumpCommand extends QApiCommand<ScreendumpCommand.Arguments, ScreendumpCommand.Response> {
	/** Compound arguments to a ScreendumpCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("filename")
		@Nonnull
		public java.lang.String filename;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("device")
		@CheckForNull
		public java.lang.String device;
		@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
		@JsonProperty("head")
		@CheckForNull
		public java.lang.Long head;

		public Arguments() {
		}

		public Arguments(java.lang.String filename, java.lang.String device, java.lang.Long head) {
			this.filename = filename;
			this.device = device;
			this.head = head;
		}
	}

	/** Response to a ScreendumpCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new ScreendumpCommand. */
	public ScreendumpCommand(@Nonnull ScreendumpCommand.Arguments argument) {
		super("screendump", Response.class, argument);
	}

	/** Constructs a new ScreendumpCommand. */
	public ScreendumpCommand(java.lang.String filename, java.lang.String device, java.lang.Long head) {
		this(new Arguments(filename, device, head));
	}
}
