package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiTypeDescriptor{name=SpiceServerInfo, data={*auth=str}, innerTypes=null}</pre>
 */
// QApiTypeDescriptor{name=SpiceServerInfo, data={*auth=str}, innerTypes=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class SpiceServerInfo extends SpiceBasicInfo {

	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("auth")
	@CheckForNull
	public java.lang.String auth;

	@Nonnull
	public SpiceServerInfo withAuth(java.lang.String value) {
		this.auth = value;
		return this;
	}

	public SpiceServerInfo() {
	}

	public SpiceServerInfo(java.lang.String auth) {
		this.auth = auth;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("auth");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("auth".equals(name))
			return auth;
		return super.getFieldByName(name);
	}
}
