package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEnumDescriptor{name=SshHostKeyCheckHashType, data=[md5, sha1], fields=null}</pre>
 */
// QApiEnumDescriptor{name=SshHostKeyCheckHashType, data=[md5, sha1], fields=null}
public enum SshHostKeyCheckHashType {
	md5("md5"),
	sha1("sha1"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ SshHostKeyCheckHashType(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
