package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiEnumDescriptor{name=TpmType, data=[passthrough], fields=null}</pre></p>
 */
// QApiEnumDescriptor{name=TpmType, data=[passthrough], fields=null}
public enum TpmType {
	// @JsonProperty("passthrough")
	passthrough("passthrough"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ TpmType(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
