package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEnumDescriptor{name=TpmType, data=[passthrough, emulator], fields=null}</pre>
 */
// QApiEnumDescriptor{name=TpmType, data=[passthrough, emulator], fields=null}
public enum TpmType {
	passthrough("passthrough"),
	emulator("emulator"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ TpmType(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
