package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=trace-event-set-state, returns=null, data={name=str, enable=bool, *ignore-unavailable=bool}}</pre>
 */
// QApiCommandDescriptor{name=trace-event-set-state, returns=null, data={name=str, enable=bool, *ignore-unavailable=bool}}
public class TraceEventSetStateCommand extends QApiCommand<TraceEventSetStateCommand.Arguments, TraceEventSetStateCommand.Response> {
	/** Compound arguments to a TraceEventSetStateCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		@JsonProperty("name")
		@Nonnull
		public java.lang.String name;
		@JsonProperty("enable")
		@Nonnull
		public boolean enable;
		@JsonProperty("ignore-unavailable")
		@CheckForNull
		public java.lang.Boolean ignoreUnavailable;

		public Arguments() {
		}

		public Arguments(java.lang.String name, boolean enable, java.lang.Boolean ignoreUnavailable) {
			this.name = name;
			this.enable = enable;
			this.ignoreUnavailable = ignoreUnavailable;
		}
	}

	/** Response to a TraceEventSetStateCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new TraceEventSetStateCommand. */
	public TraceEventSetStateCommand(@Nonnull TraceEventSetStateCommand.Arguments argument) {
		super("trace-event-set-state", Response.class, argument);
	}

	/** Constructs a new TraceEventSetStateCommand. */
	public TraceEventSetStateCommand(java.lang.String name, boolean enable, java.lang.Boolean ignoreUnavailable) {
		this(new Arguments(name, enable, ignoreUnavailable));
	}
}
