package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiStructDescriptor{name=UnixSocketAddress, data={path=str}, innerTypes=null, fields=null, base=null}</pre>
 */
// QApiStructDescriptor{name=UnixSocketAddress, data={path=str}, innerTypes=null, fields=null, base=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class UnixSocketAddress extends QApiType {

	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("path")
	@Nonnull
	public java.lang.String path;

	@Nonnull
	public UnixSocketAddress withPath(java.lang.String value) {
		this.path = value;
		return this;
	}

	public UnixSocketAddress() {
	}

	public UnixSocketAddress(java.lang.String path) {
		this.path = path;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("path");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("path".equals(name))
			return path;
		return super.getFieldByName(name);
	}
}
