package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiTypeDescriptor{name=UuidInfo, data={UUID=str}, innerTypes=null}</pre>
 */
// QApiTypeDescriptor{name=UuidInfo, data={UUID=str}, innerTypes=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class UuidInfo extends QApiType {

	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("UUID")
	@Nonnull
	public java.lang.String uuid;

	@Nonnull
	public UuidInfo withUuid(java.lang.String value) {
		this.uuid = value;
		return this;
	}

	public UuidInfo() {
	}

	public UuidInfo(java.lang.String uuid) {
		this.uuid = uuid;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("UUID");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("UUID".equals(name))
			return uuid;
		return super.getFieldByName(name);
	}
}
