package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiTypeDescriptor{name=VncBasicInfo, data={host=str, service=str, family=NetworkAddressFamily, websocket=bool}, innerTypes=null}</pre>
 */
// QApiTypeDescriptor{name=VncBasicInfo, data={host=str, service=str, family=NetworkAddressFamily, websocket=bool}, innerTypes=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class VncBasicInfo extends QApiType {

	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("host")
	@Nonnull
	public java.lang.String host;
	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("service")
	@Nonnull
	public java.lang.String service;
	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("family")
	@Nonnull
	public NetworkAddressFamily family;
	@SuppressFBWarnings("NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR")
	@JsonProperty("websocket")
	@Nonnull
	public boolean websocket;

	@Nonnull
	public VncBasicInfo withHost(java.lang.String value) {
		this.host = value;
		return this;
	}

	@Nonnull
	public VncBasicInfo withService(java.lang.String value) {
		this.service = value;
		return this;
	}

	@Nonnull
	public VncBasicInfo withFamily(NetworkAddressFamily value) {
		this.family = value;
		return this;
	}

	@Nonnull
	public VncBasicInfo withWebsocket(boolean value) {
		this.websocket = value;
		return this;
	}

	public VncBasicInfo() {
	}

	public VncBasicInfo(java.lang.String host, java.lang.String service, NetworkAddressFamily family, boolean websocket) {
		this.host = host;
		this.service = service;
		this.family = family;
		this.websocket = websocket;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("host");
		names.add("service");
		names.add("family");
		names.add("websocket");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("host".equals(name))
			return host;
		if ("service".equals(name))
			return service;
		if ("family".equals(name))
			return family;
		if ("websocket".equals(name))
			return websocket;
		return super.getFieldByName(name);
	}
}
