package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <p><pre>QApiEventDescriptor{name=VNC_INITIALIZED, data={server=VncServerInfo, client=VncClientInfo}}</pre></p>
 */
// QApiEventDescriptor{name=VNC_INITIALIZED, data={server=VncServerInfo, client=VncClientInfo}}
public class VncInitializedEvent extends QApiEvent {
	@JsonProperty("server")
	@Nonnull
	public VncServerInfo server;
	@JsonProperty("client")
	@Nonnull
	public VncClientInfo client;
}
