package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEnumDescriptor{name=VncVencryptSubAuth, data=[plain, tls-none, x509-none, tls-vnc, x509-vnc, tls-plain, x509-plain, tls-sasl, x509-sasl], fields=null}</pre>
 */
// QApiEnumDescriptor{name=VncVencryptSubAuth, data=[plain, tls-none, x509-none, tls-vnc, x509-vnc, tls-plain, x509-plain, tls-sasl, x509-sasl], fields=null}
public enum VncVencryptSubAuth {
	plain("plain"),
	tls_none("tls-none"),
	x509_none("x509-none"),
	tls_vnc("tls-vnc"),
	x509_vnc("x509-vnc"),
	tls_plain("tls-plain"),
	x509_plain("x509-plain"),
	tls_sasl("tls-sasl"),
	x509_sasl("x509-sasl"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ VncVencryptSubAuth(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
