package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=x-debug-block-dirty-bitmap-sha256, returns=BlockDirtyBitmapSha256, data=BlockDirtyBitmap}</pre>
 */
// QApiCommandDescriptor{name=x-debug-block-dirty-bitmap-sha256, returns=BlockDirtyBitmapSha256, data=BlockDirtyBitmap}
public class XDebugBlockDirtyBitmapSha256Command extends QApiCommand<BlockDirtyBitmap, XDebugBlockDirtyBitmapSha256Command.Response> {

	/** Response to a XDebugBlockDirtyBitmapSha256Command. */
	public static class Response extends QApiResponse<BlockDirtyBitmapSha256> {
	}

	/** Constructs a new XDebugBlockDirtyBitmapSha256Command. */
	public XDebugBlockDirtyBitmapSha256Command(@Nonnull BlockDirtyBitmap argument) {
		super("x-debug-block-dirty-bitmap-sha256", Response.class, argument);
	}

}
